var headerText = "Bullsh*t-Bingo";
var footerText = "<a href='https://github.com/AnnaGraphic/bullshit-bingo/' target='_blank'>Code available on github</a>";
var winText = "Winner";
var clickSnd = new Audio("audio/click.mp3");
var winSnd = new Audio("audio/win.mp3");
var JSONBingo = {"squares": [
  {"square": "Klimaneutralität bis 2030"},
  {"square": "Ausbau erneuerbarer Energien"},
  {"square": "Europäischer Mindestlohn"},
  {"square": "Digitalisierung vorantreiben"},
  {"square": "Schutz der Außengrenzen"},
  {"square": "Reform der EU-Institutionen"},
  {"square": "Förderung von Start-ups"},
  {"square": "Gleichberechtigung der Geschlechter"},
  {"square": "Investitionen in Bildung"},
  {"square": "Stärkung der Demokratie"},
  {"square": "Bekämpfung des Klimawandels"},
  {"square": "Senkung der CO2-Emissionen"},
  {"square": "Faire Handelspolitik"},
  {"square": "Schaffung von Arbeitsplätzen"},
  {"square": "Bessere Infrastruktur"},
  {"square": "Gesundheitssystem stärken"},
  {"square": "Mehr Transparenz"},
  {"square": "Förderung der Elektromobilität"},
  {"square": "Künstliche Intelligenz fördern"},
  {"square": "Verbraucherschutz stärken"},
  {"square": "Agrarreform"},
  {"square": "Mehr Mittel für Forschung und Entwicklung"},
  {"square": "Stärkung des Binnenmarktes"},
  {"square": "Datenschutz verbessern"},
  {"square": "Migration fair gestalten"},
  {"square": "Kulturelle Vielfalt fördern"},
  {"square": "Energieunabhängigkeit von Russland"},
  {"square": "Verbesserung der Cyber-Sicherheit"},
  {"square": "Nachhaltige Landwirtschaft"},
  {"square": "Reduzierung der Plastikverschmutzung"},
  {"square": "Bürgerbeteiligung erhöhen"},
  {"square": "Jugendprogramme ausbauen"},
  {"square": "Förderung des Tourismus"},
  {"square": "Förderung des ländlichen Raums"},
  {"square": "Mehr Unterstützung für KMU"},
  {"square": "Verkehrswende vorantreiben"},
  {"square": "Soziale Gerechtigkeit"},
  {"square": "Bekämpfung von Steuerflucht"},
  {"square": "Stärkung der Grundrechte"},
  {"square": "Bekämpfung von Desinformation"},
  {"square": "Kohäsionspolitik stärken"},
  {"square": "Unterstützung für Familien"},
  {"square": "Europäische Verteidigungspolitik"},
  {"square": "Bekämpfung von Terrorismus"},
  {"square": "Stärkung der Zusammenarbeit mit Afrika"},
  {"square": "Förderung der Kreislaufwirtschaft"},
  {"square": "Bezahlbarer Wohnraum"},
  {"square": "Verbesserung der Wasserqualität"},
  {"square": "Mehr Investitionen in die Kultur"},
  {"square": "Bekämpfung von Diskriminierung"}
]};
